### ISSUE TITLE
Entrega Trabajo Práctico N° 1 (vuelto a hacer)

### ISSUE THREAD

**Issue by LucasRebuffo** [LucasRebuffo/2020_K2001_Grupo_5#2]
@santiagoferreiros solicito correccion de TP

**Comment by santiagoferreiros** [comment]
Estimado grupo,

Estuve revisando el trabajo. Ustedes han compilado y probado la versión que me enviaron?
Primero que nada, el archivo txt dice "entrega.txt" y el archivo que abre el programa se llama "entrada.txt".

La idea del código en líneas generales parece estar bien. Aunque revisaría un poco el tema de la tabla de transición. No sé si están haciendo bien la búsqueda. Además, el corte de control que hacen con While nunca finaliza, dado que para salir del while interior se queda esperando una coma que nunca llega. Y empieza a imprimir caracteres sin sentido.

Les envío una captura

![image](https://user-images.githubusercontent.com/46604718/81206427-7cd48d80-8fa2-11ea-956b-e9e07ff13abf.png)

Espero sus comentarios,
Saludos,

Santiago

**Comment by LucasRebuffo** [comment]
Hola profe,
No tuve tiempo de revisarlo al tp. Pero pensé que estaba bien ya que use
parte del código de la versión anterior.
Ahora veo si lo puedo corregir. Pasa que estuve casi haciendo solo el tp,
ya que mis compañeros no tienen tiempo.
Pero más que nada era para saber si la lógica que utiliza la tabla era la
que usted esperaba. Para poder encarar el TP siguiente.
Desde ya muchas gracias por verlo.
Saludos.

**Comment by santiagoferreiros** [comment]
Si, esa es la idea Lucas.
De nada, comiencen con el trabajo 2 entonces.
Por favor se espera que trabaje todo el grupo
Saludos,

**Comment by LucasRebuffo** [comment]
Hola profe,
Estuve viendo lo que hice mal. Me faltó una condición en el while interno y
además el pedazo de lógica que recicle del tp anterior no funciona con el
de ahora.

**Comment by santiagoferreiros** [comment]
Si, eso es lo que yo noté, que en el while interno faltaba chequear que también podía ser EOF.
Y hay que ver algo de la lógica de chequear la tabla de transición porque no está reconociendo ninguna palabra.
