### ISSUE TITLE
Dudas

### ISSUE THREAD

**Issue by LucasRebuffo** [LucasRebuffo/2020_K2001_Grupo_5#5]
Profe, queres que se fije si estamos encaminados con el tp. Sabemos que no esta terminado, pero como falta poco para la entrega necesitamos estar seguros de lo que estamos haciendo.
Gracias saludos .

**Comment by santiagoferreiros** [comment]
Por lo que vi ya lo terminaron. Llegué tarde a responder este mensaje! Saludos =)
