### ISSUE TITLE
Entrega Trabajo Practico N°3

### ISSUE THREAD

**Issue by LucasRebuffo** [LucasRebuffo/2020_K2001_Grupo_5#6]
Solicitamos correcion @santiagoferreiros .

**Comment by santiagoferreiros** [comment]
Estimado grupo

Muy buen trabajo !
Lo único que noté, es que en la lista de caracteres no reconocidos, no sale por ejemplo la "ñ" o el signo "$"
Directamente salen por el yyout y no quedan atrapados por ninguna regla, ni por la última.

![image](https://user-images.githubusercontent.com/46604718/89236881-26d6ac80-d5c8-11ea-9cf3-a60e8cd690fc.png)

El resto está muy bien
Nota: 9

FELICITACIONES :)
